const VOCAB = [
  ["これ", "cái này"], ["レベル", "máy/ống nivo, thước thủy"], ["さげふり", "quả dọi"], ["フォームタイ", "form-tie"],
  ["セパレーター", "thanh giằng separator"], ["プラスチックコーン", "P-con, côn nhựa"], ["Pコン", "P-con"],
  ["コンパネ", "ván coppha"], ["ごうはん", "ván ép"], ["かたわく", "ván khuôn"], ["きんぞくせい", "bằng kim loại"],
  ["はくりざい", "chất tháo khuôn"], ["ぬる", "bôi/quét"], ["すいへい", "ngang"], ["すいちょく", "thẳng đứng"],
  ["したごしらえ", "chuẩn bị/gia công trước"], ["くりかえし", "lặp lại"], ["さんぎ", "thanh nẹp"], ["しきばた", "thanh kê chân"],
  ["パネル", "panel"], ["がいへき", "tường ngoài"], ["くぎ", "đinh"], ["まるのこ", "cưa tròn"], ["まるのこばん", "lưỡi cưa tròn"],
  ["パイプサポート", "cây chống ống"], ["ほじょサポート", "chống phụ"], ["すいへいつなぎ", "giằng ngang"],
  ["ねがらみクランプ", "kẹp giằng chân"], ["ターンバックル", "tăng đơ"], ["ホームタイ", "home-tie"],
  ["バイブレータ", "máy đầm dùi"], ["コンクリート", "bê tông"], ["てっきん", "cốt thép"], ["たんかんパイプ", "ống đơn"],
  ["あしば", "giàn giáo"], ["わくぐみあしば", "giàn giáo khung"], ["きゃたつ", "thang chữ A"], ["ローリングタワー", "giàn giáo di động"],
  ["あんぜんたい", "dây an toàn"], ["ほごぼう", "mũ bảo hộ"], ["あごひも", "dây cằm"], ["ほごめがね", "kính bảo hộ"],
  ["ほごぐ", "đồ bảo hộ"], ["てぶくろ", "găng tay"], ["ぼうじんマスク", "mặt nạ chống bụi"], ["さぎょう", "công việc"],
  ["てんけん", "kiểm tra"], ["かいたい", "tháo dỡ"], ["こてい", "cố định"], ["とりつけ", "lắp đặt"], ["くみたて", "lắp dựng"],
  ["たかいところ", "nơi cao"], ["2m いじょう", "từ 2 m trở lên"], ["せいりせいとん", "sắp xếp gọn gàng"],
];

const EXAMS = [
  {
    id: "de1",
    title: "Đề 1 - 型枠 基2 - Trang 1-2",
    questions: [
      { id: 1, page: 1, jp: "これは さげふりです。", romaji: "Kore wa sagefuri desu.", vi: "Đây là quả dọi.", answer: true, reason: "Hình trong tài liệu là quả dọi dùng với dây để kiểm tra phương thẳng đứng." },
      { id: 2, page: 1, jp: "さげふりは すいへいを だすときに つかいます。", romaji: "Sagefuri wa suihei o dasu toki ni tsukaimasu.", vi: "Quả dọi dùng khi lấy đường ngang.", answer: false, reason: "Quả dọi dùng để lấy phương thẳng đứng, không phải lấy đường ngang." },
      { id: 3, page: 1, jp: "セパレーターは Bがた BCがた Hがたがあります。", romaji: "Separeta wa B-gata, BC-gata, H-gata ga arimasu.", vi: "Separator có các loại B, BC và H.", answer: true, reason: "Tài liệu nêu các kiểu separator theo cấu tạo đầu nối như B, BC, H." },
      { id: 4, page: 1, jp: "コンパネは たいようの あたる ところに ながいじかん おいても よいです。", romaji: "Konpane wa taiyo no ataru tokoro ni nagai jikan oitemo yoi desu.", vi: "Có thể để ván coppha lâu ở nơi có nắng chiếu.", answer: false, reason: "Phơi nắng lâu làm ván cong, nứt và giảm chất lượng. Cần bảo quản đúng cách." },
      { id: 5, page: 1, jp: "きんぞくせいかたわくには はくりざいを ぬらなくても よいです。", romaji: "Kinzokusei katawaku ni wa hakurizai o nuranakutemo yoi desu.", vi: "Ván khuôn kim loại không cần bôi chất tháo khuôn.", answer: false, reason: "Ván khuôn kim loại vẫn cần chất tháo khuôn để tháo dễ và bảo vệ bề mặt." },
      { id: 6, page: 1, jp: "コンパネは たいすいせいの ものを つかいます。", romaji: "Konpane wa taisuisei no mono o tsukaimasu.", vi: "Ván coppha dùng loại chịu nước.", answer: true, reason: "Ván khuôn tiếp xúc nước và hồ xi măng nên cần loại có tính chịu nước." },
      { id: 7, page: 1, jp: "セパレーターは コンクリートのなかに うちこんでしまう ものです。", romaji: "Separeta wa konkurito no naka ni uchikonde shimau mono desu.", vi: "Separator là vật nằm lại trong bê tông.", answer: true, reason: "Phần thân separator thường bị chôn lại trong bê tông sau khi đổ." },
      { id: 8, page: 1, jp: "がいへきパネルの したごしらえは くりかえし つかえるように つくります。", romaji: "Gaiheki paneru no shitagoshirae wa kurikaeshi tsukaeru yo ni tsukurimasu.", vi: "Chuẩn bị panel tường ngoài để có thể dùng lặp lại.", answer: true, reason: "Ván khuôn nên được gia công chắc và dễ tháo để tái sử dụng." },
      { id: 9, page: 1, jp: "したごしらえでわからないときは じぶんでかんがえてつくります。", romaji: "Shitagoshirae de wakaranai toki wa jibun de kangaete tsukurimasu.", vi: "Không hiểu phần chuẩn bị thì tự suy nghĩ rồi làm.", answer: false, reason: "Khi không hiểu phải hỏi người phụ trách hoặc xác nhận bản vẽ, không tự ý làm." },
      { id: 10, page: 1, jp: "すいへいつなぎは いちほうこうに とりつければ よいです。", romaji: "Suihei-tsunagi wa ichi-hoko ni toritsukereba yoi desu.", vi: "Giằng ngang chỉ cần lắp một hướng.", answer: false, reason: "Hệ chống cần ổn định theo các phương cần thiết, một hướng thường không đủ." },
      { id: 11, page: 1, jp: "がいへきパネルの したには しきばたを つかいます。", romaji: "Gaiheki paneru no shita ni wa shikibata o tsukaimasu.", vi: "Bên dưới panel tường ngoài dùng thanh kê chân.", answer: true, reason: "しきばた dùng để định vị chân panel và giữ cao độ." },
      { id: 12, page: 1, jp: "コンパネや さんぎは くりかえして つかえるように くみたてます。", romaji: "Konpane ya sangi wa kurikaeshite tsukaeru yo ni kumitatemasu.", vi: "Ván coppha và thanh nẹp được lắp để tái sử dụng.", answer: true, reason: "Lắp dựng cần nghĩ đến tháo dỡ và dùng lại vật liệu." },
      { id: 13, page: 1, jp: "セパレーターに ホームタイを つけるときは かなならず ホームタイが まわるまで まわし しっかりと つけます。", romaji: "Separeta ni homutai o tsukeru toki wa kanarazu homutai ga mawaru made mawashi shikkari to tsukemasu.", vi: "Khi gắn home-tie vào separator phải vặn chắc.", answer: true, reason: "Home-tie phải được siết chắc để giữ khoảng cách ván khuôn khi đổ bê tông." },
      { id: 14, page: 2, jp: "パネルかたわくは こわさないように ていねいに かいたいします。", romaji: "Paneru katawaku wa kowasanai yo ni teinei ni kaitai shimasu.", vi: "Tháo ván khuôn panel cẩn thận để không làm hỏng.", answer: true, reason: "Tháo khuôn đúng trình tự giúp tái sử dụng vật liệu và tránh tai nạn." },
      { id: 15, page: 2, jp: "パイプレータは なるべくながく かけたほうが よいです。", romaji: "Paipureta wa narubeku nagaku kaketa ho ga yoi desu.", vi: "Pipe support nên kéo càng dài càng tốt.", answer: false, reason: "Kéo dài quá mức làm giảm ổn định. Phải dùng đúng chiều dài cho phép." },
      { id: 16, page: 2, jp: "かたわくを しめつけるのに たんかんぱいぷは つかいません。", romaji: "Katawaku o shimetsukeru noni tankan-paipu wa tsukaimasen.", vi: "Không dùng ống đơn để siết ván khuôn.", answer: true, reason: "Siết ván khuôn phải dùng phụ kiện đúng mục đích như separator/form-tie." },
      { id: 17, page: 2, jp: "まるのこばんは つかうまえに てんけんを します。", romaji: "Marunoko-ban wa tsukau mae ni tenken o shimasu.", vi: "Lưỡi cưa tròn phải kiểm tra trước khi dùng.", answer: true, reason: "Kiểm tra lưỡi, nắp bảo vệ và máy trước khi dùng là yêu cầu an toàn." },
      { id: 18, page: 2, jp: "あしばを くみたてるときは あんぜんたいを つけます。", romaji: "Ashiba o kumitateru toki wa anzentai o tsukemasu.", vi: "Khi lắp giàn giáo thì đeo dây an toàn.", answer: true, reason: "Lắp giàn giáo có nguy cơ ngã cao nên phải dùng dây an toàn." },
      { id: 19, page: 2, jp: "2m いじょうの たかいところで さぎょうを するときは あんぜんたいを つけます。", romaji: "Ni-metorui jo no takai tokoro de sagyo o suru toki wa anzentai o tsukemasu.", vi: "Làm việc ở nơi cao từ 2 m trở lên thì đeo dây an toàn.", answer: true, reason: "Mốc 2 m là nội dung an toàn lao động thường gặp trong đề." },
      { id: 20, page: 2, jp: "はきものは さぎょうに てきしたものを はきます。", romaji: "Hakimono wa sagyo ni tekishita mono o hakimasu.", vi: "Giày dép phải phù hợp với công việc.", answer: true, reason: "Cần dùng giày bảo hộ/phù hợp để chống trượt và bảo vệ bàn chân." },
    ],
  },
  {
    id: "de2",
    title: "Đề 2 - 型枠 基2 - Trang 3-4",
    questions: [
      { id: 1, page: 3, jp: "これは プラスチックコーン（Pコン）です。", romaji: "Kore wa purasuchikku kon (P-kon) desu.", vi: "Đây là côn nhựa P-con.", answer: true, reason: "Hình vẽ là P-con dùng cùng separator/form-tie." },
      { id: 2, page: 3, jp: "さげふりは すいちょくを だすときに つかいます。", romaji: "Sagefuri wa suichoku o dasu toki ni tsukaimasu.", vi: "Quả dọi dùng để lấy phương thẳng đứng.", answer: true, reason: "さげふり kiểm tra độ thẳng đứng của cột, tường hoặc ván khuôn." },
      { id: 3, page: 3, jp: "Bがたのセパレーターとは Pコンが りょうがわについている セパレーターのことです。", romaji: "B-gata no separeta to wa P-kon ga ryogawa ni tsuite iru separeta no koto desu.", vi: "Separator loại B là loại có P-con ở hai bên.", answer: true, reason: "Loại B thường có P-con ở hai phía để liên kết hai mặt ván." },
      { id: 4, page: 3, jp: "ごうはんせいかたわくは くりかえし つかいません。", romaji: "Gohansei katawaku wa kurikaeshi tsukaimasen.", vi: "Ván khuôn gỗ ép không dùng lặp lại.", answer: false, reason: "Ván khuôn gỗ ép vẫn được dùng lại nếu tháo và bảo quản đúng cách." },
      { id: 5, page: 3, jp: "とそうごうはんには はくりざいは つかいません。", romaji: "Toso gohan ni wa hakurizai wa tsukaimasen.", vi: "Ván ép phủ sơn không dùng chất tháo khuôn.", answer: false, reason: "Bề mặt phủ vẫn cần xử lý/chất tháo khuôn theo điều kiện thi công để tháo dễ và giữ bề mặt bê tông." },
      { id: 6, page: 3, jp: "かたわくには ごうはんせいかたわく きんぞくせいかたわくなどが あります。", romaji: "Katawaku ni wa gohansei katawaku, kinzokusei katawaku nado ga arimasu.", vi: "Ván khuôn có loại ván ép, loại kim loại, v.v.", answer: true, reason: "Vật liệu ván khuôn gồm gỗ ép, kim loại và các loại khác." },
      { id: 7, page: 3, jp: "ねがらみクランプとは パイプサポートを こていするものです。", romaji: "Negarami kuranpu to wa paipu sapoto o kotei suru mono desu.", vi: "Kẹp giằng chân là vật để cố định pipe support.", answer: true, reason: "ねがらみクランプ dùng để giữ/cố định phần chân hệ chống ống." },
      { id: 8, page: 3, jp: "したごしらえに つかうくぎの ながさは 70mmです。", romaji: "Shitagoshirae ni tsukau kugi no nagasa wa 70 mm desu.", vi: "Đinh dùng cho chuẩn bị ván khuôn dài 70 mm.", answer: false, reason: "Tài liệu khác trong bộ nêu chiều dài thường dùng là 45-50 mm và 65 mm, không cố định 70 mm." },
      { id: 9, page: 3, jp: "だいのこ（まるのこばん）は ふたりひとくみで つかうほうが よいです。", romaji: "Dainoko (marunoko-ban) wa futari hitokumi de tsukau ho ga yoi desu.", vi: "Cưa tròn nên dùng hai người một nhóm.", answer: false, reason: "Cưa tròn cầm tay phải do người sử dụng điều khiển đúng cách, không phải hai người cùng cầm." },
      { id: 10, page: 3, jp: "パイプサポートは ちょくせつ コンパネを ささえます。", romaji: "Paipu sapoto wa chokusetsu konpane o sasaemasu.", vi: "Pipe support đỡ trực tiếp ván coppha.", answer: false, reason: "Pipe support thường đỡ hệ đà/giá đỡ, không đặt trực tiếp lên tấm ván một cách tùy tiện." },
      { id: 11, page: 3, jp: "パイプサポートの すいへいつなぎは たかさ3mごとに とりつけます。", romaji: "Paipu sapoto no suihei-tsunagi wa takasa 3 m goto ni toritsukemasu.", vi: "Giằng ngang của pipe support lắp mỗi 3 m chiều cao.", answer: false, reason: "Khoảng cách giằng phải theo quy định/bản vẽ; câu 3 m cố định trong đề này là sai." },
      { id: 12, page: 3, jp: "ほじょサポートは パイプサポートの したに とりつけます。", romaji: "Hojo sapoto wa paipu sapoto no shita ni toritsukemasu.", vi: "Chống phụ được lắp bên dưới pipe support.", answer: false, reason: "Chống phụ không được lắp tùy tiện dưới pipe support; phải theo cấu tạo chống đỡ đúng." },
      { id: 13, page: 3, jp: "しきさんぎは たかさを きめて すいへいに ゆかに とめます。", romaji: "Shiki-sangi wa takasa o kimete suihei ni yuka ni tomemasu.", vi: "Thanh kê/nẹp đặt theo cao độ và cố định ngang trên sàn.", answer: true, reason: "しきさんぎ/しきばた dùng để lấy vị trí, cao độ và giữ chân ván khuôn." },
      { id: 14, page: 3, jp: "かたわくを しめている パイプを とったら すぐに パネルの かいたいに はいります。", romaji: "Katawaku o shimete iru paipu o tottara suguni paneru no kaitai ni hairimasu.", vi: "Sau khi tháo ống đang siết ván khuôn thì lập tức tháo panel.", answer: false, reason: "Tháo dỡ phải theo trình tự an toàn, không tự ý tháo bộ phận giữ rồi vào tháo panel ngay." },
      { id: 15, page: 4, jp: "コンクリートだせつに バイブレータを つかうばあいは てっきんに ちょくせつあてて しんどうを つたえるようにすると よいです。", romaji: "Konkurito dasetsu ni baibureta o tsukau baai wa tekkin ni chokusetsu atete shindo o tsutaeru yo ni suru to yoi desu.", vi: "Khi đổ bê tông dùng đầm dùi thì chạm trực tiếp vào cốt thép để truyền rung.", answer: false, reason: "Không chạm trực tiếp đầm dùi vào cốt thép vì dễ làm lệch thép và phân tầng bê tông." },
      { id: 16, page: 4, jp: "たんかんパイプには まるがたと かくがたが あります。", romaji: "Tankan paipu ni wa marugata to kakugata ga arimasu.", vi: "Ống đơn có loại tròn và loại vuông.", answer: false, reason: "たんかんパイプ thông thường là ống thép tròn dùng cho giàn giáo/chống đỡ." },
      { id: 17, page: 4, jp: "まるのこばんを つかうときは てぶくろを します。", romaji: "Marunoko-ban o tsukau toki wa tebukuro o shimasu.", vi: "Khi dùng cưa tròn thì đeo găng tay.", answer: false, reason: "Găng tay có thể bị cuốn vào lưỡi cưa; khi dùng máy quay phải theo quy định an toàn." },
      { id: 18, page: 4, jp: "きゃたつを つかって さぎょうをするときは きゃたつの いちばんうえに たっても よいです。", romaji: "Kyatatsu o tsukatte sagyo o suru toki wa kyatatsu no ichiban ue ni tattemo yoi desu.", vi: "Khi làm trên thang chữ A có thể đứng trên bậc trên cùng.", answer: false, reason: "Không đứng trên bậc/đỉnh trên cùng của thang chữ A vì rất dễ ngã." },
      { id: 19, page: 4, jp: "コンクリートくぎを うつときは ほごめがねは いりません。", romaji: "Konkurito kugi o utsu toki wa hogomegane wa irimasen.", vi: "Đóng đinh bê tông thì không cần kính bảo hộ.", answer: false, reason: "Đóng đinh bê tông có nguy cơ mảnh văng, cần kính bảo hộ." },
      { id: 20, page: 4, jp: "あぶらのついた こうぐを つかっても よいです。", romaji: "Abura no tsuita kogu o tsukattemo yoi desu.", vi: "Có thể dùng dụng cụ dính dầu.", answer: false, reason: "Dụng cụ dính dầu dễ trơn tuột và gây tai nạn, cần lau sạch trước khi dùng." },
    ],
  },
  {
    id: "de3",
    title: "Đề 3 - 型枠 基2 - Trang 5-6",
    questions: [
      { id: 1, page: 5, jp: "これは セパレーターです。", romaji: "Kore wa separeta desu.", vi: "Đây là separator.", answer: true, reason: "Hình trong đề là thanh separator dùng giữ khoảng cách hai mặt ván khuôn." },
      { id: 2, page: 5, jp: "これは しんずみです。", romaji: "Kore wa shinzumi desu.", vi: "Đây là mực tim/đường tim.", answer: false, reason: "Hình không phải đường tim trên mặt bằng; cần phân biệt dụng cụ/vật liệu với ký hiệu đường tim." },
      { id: 3, page: 5, jp: "めんぎを うつときは めんぎくぎを つかいます。", romaji: "Mengi o utsu toki wa mengi-kugi o tsukaimasu.", vi: "Khi đóng nẹp mép thì dùng đinh dành cho nẹp mép.", answer: true, reason: "めんぎ cần dùng đúng loại đinh để cố định chắc và dễ tháo." },
      { id: 4, page: 5, jp: "これは わくぐみあしばに つかいます。", romaji: "Kore wa wakugumi ashiba ni tsukaimasu.", vi: "Cái này dùng cho giàn giáo khung.", answer: true, reason: "Hình trong đề là bộ phận dùng trong hệ giàn giáo khung." },
      { id: 5, page: 5, jp: "コンパネは たいようの あたるところに ながいじかん おいても よいです。", romaji: "Konpane wa taiyo no ataru tokoro ni nagaijikan oitemo yoi desu.", vi: "Có thể để ván coppha lâu dưới nắng.", answer: false, reason: "Nắng làm cong vênh và giảm chất lượng ván, cần bảo quản tránh nắng mưa trực tiếp." },
      { id: 6, page: 5, jp: "ごうはんせいかたわくと きんぞくせいかたわくは いっしょに つかえません。", romaji: "Gohansei katawaku to kinzokusei katawaku wa isshoni tsukaemasen.", vi: "Ván khuôn gỗ ép và ván khuôn kim loại không thể dùng cùng nhau.", answer: false, reason: "Có thể kết hợp nhiều loại ván khuôn nếu thiết kế và liên kết đúng." },
      { id: 7, page: 5, jp: "ターンバックルは コンパネと さんぎを つなぐものです。", romaji: "Tanbakkuru wa konpane to sangi o tsunagu mono desu.", vi: "Tăng đơ là vật nối ván coppha với thanh nẹp.", answer: false, reason: "ターンバックル dùng để căng/chỉnh giằng, không phải vật nối trực tiếp compane với sangi." },
      { id: 8, page: 6, jp: "はしらかたわくの したごしらえは したごしらえず（かこうず）に よって つくります。", romaji: "Hashira katawaku no shitagoshirae wa shitagoshirae-zu (kako-zu) ni yotte tsukurimasu.", vi: "Chuẩn bị ván khuôn cột dựa theo bản vẽ gia công.", answer: true, reason: "Gia công ván khuôn phải theo bản vẽ/bảng gia công để đúng kích thước." },
      { id: 9, page: 6, jp: "かたわくに おおく つかわれる くぎの ながさは 45mm～50mmと 65mmです。", romaji: "Katawaku ni oku tsukawareru kugi no nagasa wa 45 mm kara 50 mm to 65 mm desu.", vi: "Đinh hay dùng cho ván khuôn dài 45-50 mm và 65 mm.", answer: true, reason: "Đây là các chiều dài đinh phổ biến trong gia công/lắp dựng ván khuôn." },
      { id: 10, page: 6, jp: "さんぎは かたわくを くみたてるために つかいます。", romaji: "Sangi wa katawaku o kumitateru tame ni tsukaimasu.", vi: "Thanh nẹp dùng để lắp dựng ván khuôn.", answer: true, reason: "さんぎ dùng làm nẹp/đà phụ để liên kết, giữ và gia cường panel." },
      { id: 11, page: 6, jp: "すいへいつなぎは いちほうこうに とりつければ よいです。", romaji: "Suihei-tsunagi wa ichi-hoko ni toritsukereba yoi desu.", vi: "Giằng ngang chỉ cần lắp một hướng.", answer: false, reason: "Giằng phải bảo đảm ổn định tổng thể, không chỉ lắp một hướng cho đủ." },
      { id: 12, page: 6, jp: "パイプサポートを つないで つかうときは 2ほんまでとします。", romaji: "Paipu sapoto o tsunaide tsukau toki wa nihon made to shimasu.", vi: "Khi nối pipe support để dùng thì tối đa hai cây.", answer: true, reason: "Nếu nối pipe support phải theo giới hạn cho phép; nội dung đề nêu tối đa hai cây." },
      { id: 13, page: 6, jp: "うちはなし かたわくには Cかた セパレーターを つかいます。", romaji: "Uchihanashi katawaku ni wa C-kata separeta o tsukaimasu.", vi: "Ván khuôn bê tông trần dùng separator loại C.", answer: true, reason: "Bê tông trần cần phụ kiện phù hợp bề mặt hoàn thiện, trong đó có loại C." },
      { id: 14, page: 6, jp: "かいたいには かいたいようの バールは ひつよう ありません。", romaji: "Kaitai ni wa kaitaiyo no baru wa hitsuyo arimasen.", vi: "Khi tháo dỡ không cần xà beng tháo dỡ.", answer: false, reason: "Tháo dỡ cần dụng cụ đúng mục đích để an toàn và tránh hỏng vật liệu." },
      { id: 15, page: 6, jp: "かたくて うちにくくなった コンクリートは げんばで みずをいれて やわらかくします。", romaji: "Katakute uchinikuku natta konkurito wa genba de mizu o irete yawarakaku shimasu.", vi: "Bê tông bị cứng, khó đổ thì thêm nước tại công trường cho mềm.", answer: false, reason: "Không tự ý thêm nước vì làm giảm cường độ và chất lượng bê tông." },
      { id: 16, page: 6, jp: "パネルを つくるときの ベニヤは あつみ5.5mmを いつも つかいます。", romaji: "Paneru o tsukuru toki no beniya wa atsumi 5.5 mm o itsumo tsukaimasu.", vi: "Khi làm panel luôn dùng ván veneer dày 5.5 mm.", answer: false, reason: "Chiều dày ván phải theo thiết kế và mục đích, không phải lúc nào cũng 5.5 mm." },
      { id: 17, page: 6, jp: "ほごぼうの あごひもは しめなくては いけません。", romaji: "Hogobo no ago-himo wa shimenakute wa ikemasen.", vi: "Dây cằm của mũ bảo hộ phải được cài/siết.", answer: true, reason: "Cài dây cằm giúp mũ không rơi khi cúi hoặc khi có va chạm." },
      { id: 18, page: 6, jp: "まるのこばんは つかうまえに てんけんを します。", romaji: "Marunoko-ban wa tsukau mae ni tenken o shimasu.", vi: "Lưỡi cưa tròn phải kiểm tra trước khi dùng.", answer: true, reason: "Kiểm tra trước khi vận hành là yêu cầu an toàn bắt buộc." },
      { id: 19, page: 6, jp: "けんちくこうじげんばでは つねに せいりせいとんをして あんぜんに さぎょうを しなければなりません。", romaji: "Kenchiku koji genba de wa tsuneni seiri-seiton o shite anzen ni sagyo o shinakereba narimasen.", vi: "Ở công trường xây dựng phải luôn sắp xếp gọn gàng để làm việc an toàn.", answer: true, reason: "Seiri-seiton giúp tránh vấp ngã, va chạm và thất lạc dụng cụ." },
      { id: 20, page: 6, jp: "でんきの スイッチには ぬれたてで さわっても よいです。", romaji: "Denki no suitchi ni wa nureta te de sawattemo yoi desu.", vi: "Có thể chạm công tắc điện bằng tay ướt.", answer: false, reason: "Tay ướt dễ gây điện giật, tuyệt đối không chạm thiết bị điện." },
    ],
  },
  {
    id: "de4",
    title: "Đề 4 - 型枠 基2 - Trang 7-8",
    questions: [
      { id: 1, page: 7, jp: "これは フォームタイです。", romaji: "Kore wa fomu-tai desu.", vi: "Đây là form-tie.", answer: true, reason: "Hình là phụ kiện form-tie dùng siết hai mặt ván khuôn." },
      { id: 2, page: 7, jp: "これは ねがらみクランプです。", romaji: "Kore wa negarami kuranpu desu.", vi: "Đây là kẹp giằng chân.", answer: true, reason: "Hình là loại clamp dùng cho giằng chân/chống ống." },
      { id: 3, page: 7, jp: "レベルは かたに かついで もちます。", romaji: "Reberu wa kata ni katsuide mochimasu.", vi: "Máy level được vác trên vai để mang.", answer: false, reason: "Dụng cụ đo phải vận chuyển cẩn thận trong hộp/đúng tư thế, không vác tùy tiện trên vai." },
      { id: 4, page: 7, jp: "これは わくぐみあしばです。", romaji: "Kore wa wakugumi ashiba desu.", vi: "Đây là giàn giáo khung.", answer: true, reason: "Hình vẽ là hệ giàn giáo khung." },
      { id: 5, page: 7, jp: "ごうはんせいかたわくは くりかえし つかいません。", romaji: "Gohansei katawaku wa kurikaeshi tsukaimasen.", vi: "Ván khuôn gỗ ép không dùng lại.", answer: false, reason: "Ván khuôn gỗ ép có thể tái sử dụng nếu tháo và bảo quản đúng." },
      { id: 6, page: 7, jp: "きんぞくせいかたわくには はくりざいを ぬらなくても よいです。", romaji: "Kinzokusei katawaku ni wa hakurizai o nuranakutemo yoi desu.", vi: "Ván khuôn kim loại không cần bôi chất tháo khuôn.", answer: false, reason: "Ván khuôn kim loại vẫn cần bôi chất tháo khuôn." },
      { id: 7, page: 7, jp: "ごうはんパネルの 3×6とは はば900mm ながさ1,800mmの すんぽうを いいます。", romaji: "Gohan paneru no san-roku to wa haba 900 mm nagasa 1,800 mm no sunpo o iimasu.", vi: "Panel 3×6 nghĩa là rộng 900 mm, dài 1.800 mm.", answer: true, reason: "3×6 là kích thước tấm phổ biến 900 mm x 1.800 mm." },
      { id: 8, page: 7, jp: "おおがたパネルの したごしらえは くぎを すくなくして うちます。", romaji: "Ogata paneru no shitagoshirae wa kugi o sukunakushite uchimasu.", vi: "Chuẩn bị panel lớn thì đóng ít đinh hơn.", answer: true, reason: "Giảm đinh hợp lý giúp tháo dễ, hạn chế hỏng và tái sử dụng panel." },
      { id: 9, page: 7, jp: "はくりざいを ぬるときは ゆかに シートなどを しきます。", romaji: "Hakurizai o nuru toki wa yuka ni shito nado o shikimasu.", vi: "Khi bôi chất tháo khuôn thì trải tấm lót trên sàn.", answer: true, reason: "Trải sheet giúp chống bẩn/trơn sàn do chất tháo khuôn." },
      { id: 10, page: 7, jp: "かたわくは すきまが あるように くみたてます。", romaji: "Katawaku wa sukima ga aru yo ni kumitatemasu.", vi: "Lắp ván khuôn để có khe hở.", answer: false, reason: "Ván khuôn phải kín khít để không rò vữa bê tông." },
      { id: 11, page: 8, jp: "パイプサポートは ちょくせつ コンパネを ささえます。", romaji: "Paipu sapoto wa chokusetsu konpane o sasaemasu.", vi: "Pipe support đỡ trực tiếp ván coppha.", answer: false, reason: "Cần hệ đà/giá đỡ đúng cấu tạo, không chống trực tiếp vào tấm ván tùy tiện." },
      { id: 12, page: 8, jp: "がいへきパネルの したには しきばたを つかいます。", romaji: "Gaiheki paneru no shita ni wa shikibata o tsukaimasu.", vi: "Dưới panel tường ngoài dùng thanh kê chân.", answer: true, reason: "しきばた dùng định vị chân panel tường ngoài." },
      { id: 13, page: 8, jp: "パイプサポートを ななめに たてるときは あしもとが うごかないように します。", romaji: "Paipu sapoto o naname ni tateru toki wa ashimoto ga ugokanai yo ni shimasu.", vi: "Khi dựng pipe support nghiêng, phải làm sao cho chân không dịch chuyển.", answer: true, reason: "Chân chống phải được giữ chắc để tránh trượt và sập đỡ." },
      { id: 14, page: 8, jp: "かいたいで さんぎは おっても かまいません。", romaji: "Kaitai de sangi wa otte mo kamaimasen.", vi: "Khi tháo dỡ có thể bẻ gãy thanh nẹp cũng được.", answer: false, reason: "Tháo dỡ phải tránh làm hỏng vật liệu để tái sử dụng và tránh mảnh văng." },
      { id: 15, page: 8, jp: "コンクリートは こおらせては いけません。", romaji: "Konkurito wa korasete wa ikemasen.", vi: "Không được để bê tông bị đông lạnh.", answer: true, reason: "Bê tông bị đóng băng ảnh hưởng nghiêm trọng đến cường độ và chất lượng." },
      { id: 16, page: 8, jp: "コンパネは 2×6（600mm×1800mm）と 3×6（900mm×1800mm）が おおく つかわれます。", romaji: "Konpane wa ni-roku to san-roku ga oku tsukawaremasu.", vi: "Ván coppha thường dùng loại 2×6 và 3×6.", answer: true, reason: "Đây là các kích thước tấm ván thông dụng." },
      { id: 17, page: 8, jp: "かたわくを くみたてるときは ほごぼうを かぶります。", romaji: "Katawaku o kumitateru toki wa hogobo o kaburimasu.", vi: "Khi lắp dựng ván khuôn thì đội mũ bảo hộ.", answer: true, reason: "Mũ bảo hộ là trang bị bắt buộc để tránh vật rơi/va đập." },
      { id: 18, page: 8, jp: "まるのこばんを つかうときは てぶくろを します。", romaji: "Marunoko-ban o tsukau toki wa tebukuro o shimasu.", vi: "Khi dùng cưa tròn thì đeo găng tay.", answer: false, reason: "Găng tay có thể bị cuốn vào lưỡi cưa, nên câu này sai." },
      { id: 19, page: 8, jp: "けいたいようまるのこは じぶんのものであれば しようまえ てんけんは ひつようありません。", romaji: "Keitaiyo marunoko wa jibun no mono de areba shiyo mae tenken wa hitsuyo arimasen.", vi: "Cưa tròn cá nhân thì không cần kiểm tra trước khi dùng.", answer: false, reason: "Dù là đồ cá nhân vẫn phải kiểm tra trước khi sử dụng." },
      { id: 20, page: 8, jp: "ほごぐを つけて さぎょうが しにくいときでも ほごぐは つけて さぎょうします。", romaji: "Hogogu o tsukete sagyo ga shinikui toki demo hogogu wa tsukete sagyo shimasu.", vi: "Dù khó làm việc khi đeo đồ bảo hộ, vẫn phải đeo để làm.", answer: true, reason: "Không được bỏ đồ bảo hộ vì bất tiện; an toàn là ưu tiên." },
    ],
  },
  {
    id: "de5",
    title: "Đề 5 - 2008-A - Trang 9-10",
    questions: [
      { id: 1, page: 9, jp: "レベルは かくどを しらべるときに つかいます。", romaji: "Reberu wa kakudo o shiraberu toki ni tsukaimasu.", vi: "Level dùng để kiểm tra góc.", answer: false, reason: "レベル dùng kiểm tra/lấy cao độ và phương ngang, không phải dụng cụ đo góc chính." },
      { id: 2, page: 9, jp: "フォームタイは コンクリートのなかに うちこんでしまうものです。", romaji: "Fomu-tai wa konkurito no naka ni uchikonde shimau mono desu.", vi: "Form-tie là vật sẽ nằm lại trong bê tông.", answer: false, reason: "Separator thường nằm lại trong bê tông; form-tie là phụ kiện tháo ra/sử dụng lại." },
      { id: 3, page: 9, jp: "Bがたのセパレーターとは Pコンが りょうがわについている セパレーターのことです。", romaji: "B-gata no separeta to wa P-kon ga ryogawa ni tsuite iru separeta no koto desu.", vi: "Separator loại B là loại có P-con ở hai bên.", answer: true, reason: "Loại B có P-con ở hai phía theo cấu tạo trong tài liệu." },
      { id: 4, page: 9, jp: "これは わくぐみあしばです。", romaji: "Kore wa wakugumi ashiba desu.", vi: "Đây là giàn giáo khung.", answer: true, reason: "Hình vẽ là giàn giáo khung." },
      { id: 5, page: 9, jp: "まるばしらには かみかたわくも おおく つかわれます。", romaji: "Maru-bashira ni wa kami-katawaku mo oku tsukawaremasu.", vi: "Cột tròn cũng thường dùng ván khuôn giấy.", answer: true, reason: "Ván khuôn giấy/ống giấy được dùng nhiều cho cột tròn." },
      { id: 6, page: 9, jp: "フラットデッキプレートは はしらかたわくに つかいます。", romaji: "Furatto dekki pureto wa hashira katawaku ni tsukaimasu.", vi: "Flat deck plate dùng cho ván khuôn cột.", answer: false, reason: "Flat deck plate là vật liệu sàn, không dùng làm ván khuôn cột." },
      { id: 7, page: 10, jp: "ごうはんパネルの 3×6とは はば900mm ながさ1,800mmの すんぽうを いいます。", romaji: "Gohan paneru no san-roku to wa haba 900 mm nagasa 1,800 mm no sunpo o iimasu.", vi: "Panel 3×6 là rộng 900 mm, dài 1.800 mm.", answer: true, reason: "3×6 là kích thước tấm 900 mm x 1.800 mm." },
      { id: 8, page: 10, jp: "はしらかたわくの したごしらえは したごしらえず（かこうず）によって つくります。", romaji: "Hashira katawaku no shitagoshirae wa shitagoshirae-zu (kako-zu) ni yotte tsukurimasu.", vi: "Chuẩn bị ván khuôn cột theo bản vẽ gia công.", answer: true, reason: "Phải gia công theo bản vẽ/kích thước đã chỉ định." },
      { id: 9, page: 10, jp: "はくりざいを ぬるときは ゆかに シートなどを しきます。", romaji: "Hakurizai o nuru toki wa yuka ni shito nado o shikimasu.", vi: "Khi bôi chất tháo khuôn thì trải sheet trên sàn.", answer: true, reason: "Trải sheet giúp giữ vệ sinh và chống trơn trượt do chất tháo khuôn." },
      { id: 10, page: 10, jp: "かたわくは すきまが あるように くみたてます。", romaji: "Katawaku wa sukima ga aru yo ni kumitatemasu.", vi: "Lắp ván khuôn sao cho có khe hở.", answer: false, reason: "Ván khuôn phải kín để không rò hồ/vữa bê tông." },
      { id: 11, page: 10, jp: "はしらと かべを くみたてるときは さげふりは つかいません。", romaji: "Hashira to kabe o kumitateru toki wa sagefuri wa tsukaimasen.", vi: "Khi lắp cột và tường thì không dùng quả dọi.", answer: false, reason: "Cột và tường cần kiểm tra thẳng đứng bằng quả dọi hoặc dụng cụ tương đương." },
      { id: 12, page: 10, jp: "がいへきパネルの したには しきばたを つかいます。", romaji: "Gaiheki paneru no shita ni wa shikibata o tsukaimasu.", vi: "Dưới panel tường ngoài dùng thanh kê chân.", answer: true, reason: "しきばた định vị chân panel và cao độ." },
      { id: 13, page: 10, jp: "パネルと パネルを くぎで とめるときは かならず くぎは うちこんでしまいます。", romaji: "Paneru to paneru o kugi de tomeru toki wa kanarazu kugi wa uchikonde shimaimasu.", vi: "Khi đóng đinh nối panel, nhất định đóng chìm hết đinh.", answer: false, reason: "Cần nghĩ đến tháo dỡ/tái sử dụng; không phải lúc nào cũng đóng chìm hết đinh." },
      { id: 14, page: 10, jp: "かいたいした パイプは かべに たてかけて おきます。", romaji: "Kaitai shita paipu wa kabe ni tatekakete okimasu.", vi: "Ống đã tháo thì dựng tựa vào tường.", answer: false, reason: "Ống dựng tựa có thể đổ; phải xếp gọn ở nơi quy định." },
      { id: 15, page: 10, jp: "コンクリートを うつときは バイブレータを てっきんに あてます。", romaji: "Konkurito o utsu toki wa baibureta o tekkin ni atemasu.", vi: "Khi đổ bê tông thì chạm máy đầm vào cốt thép.", answer: false, reason: "Không chạm đầm dùi trực tiếp vào cốt thép vì làm lệch thép và ảnh hưởng chất lượng." },
    ],
  },
  {
    id: "de6",
    title: "Đề 6 - 型枠 基2 - Trang 11-12",
    questions: [
      { id: 1, page: 11, jp: "これは ラチェットレンチです。", romaji: "Kore wa rachetto renchi desu.", vi: "Đây là cờ lê bánh cóc.", answer: true, reason: "Hình vẽ là ratchet wrench dùng siết/tháo bu lông, phụ kiện." },
      { id: 2, page: 11, jp: "レベルは すいへいを だすときに つかいます。", romaji: "Reberu wa suihei o dasu toki ni tsukaimasu.", vi: "Level dùng để lấy đường ngang.", answer: true, reason: "レベル dùng kiểm tra cao độ và phương ngang." },
      { id: 3, page: 11, jp: "ラチェットレンチは ばんせんを しめるときも つかいます。", romaji: "Rachetto renchi wa bansen o shimeru toki mo tsukaimasu.", vi: "Cờ lê bánh cóc cũng dùng khi siết dây thép buộc.", answer: true, reason: "Trong công trường có thể dùng ratchet wrench để siết một số phụ kiện/dây theo đúng cách." },
      { id: 4, page: 11, jp: "とそうごうはんには はくりざいは つかいません。", romaji: "Toso gohan ni wa hakurizai wa tsukaimasen.", vi: "Ván ép phủ sơn không dùng chất tháo khuôn.", answer: false, reason: "Vẫn cần xử lý chất tháo khuôn phù hợp để tháo dễ và bảo vệ bề mặt." },
      { id: 5, page: 11, jp: "ごうはんせいかたわくと きんぞくせいかたわくは いっしょに つかえません。", romaji: "Gohansei katawaku to kinzokusei katawaku wa isshoni tsukaemasen.", vi: "Ván khuôn gỗ ép và kim loại không thể dùng chung.", answer: false, reason: "Có thể dùng kết hợp nếu thiết kế, liên kết và trình tự thi công đúng." },
      { id: 6, page: 11, jp: "フラットデッキプレートは はしらかたわくに つかいます。", romaji: "Furatto dekki pureto wa hashira katawaku ni tsukaimasu.", vi: "Flat deck plate dùng cho ván khuôn cột.", answer: false, reason: "Flat deck plate dùng cho sàn, không phải ván khuôn cột." },
      { id: 7, page: 11, jp: "かたわくよう ばたかくは 130mm×130mmかくです。", romaji: "Katawaku-yo batakaku wa 130 mm x 130 mm kaku desu.", vi: "Gỗ vuông dùng cho ván khuôn là loại 130 mm × 130 mm.", answer: false, reason: "Kích thước này không phải kích thước thường dùng cho vật liệu nẹp ván khuôn trong đề." },
      { id: 8, page: 11, jp: "コンパネは できるだけ きらないように つかいます。", romaji: "Konpane wa dekiru dake kiranai yo ni tsukaimasu.", vi: "Ván coppha nên dùng sao cho ít cắt nhất có thể.", answer: true, reason: "Hạn chế cắt giúp giảm hao hụt, giữ độ bền và dễ tái sử dụng." },
      { id: 9, page: 11, jp: "したごしらえは かこうちょうを みて そのとおりに つくります。", romaji: "Shitagoshirae wa kakocho o mite sono tori ni tsukurimasu.", vi: "Chuẩn bị/gia công theo đúng bảng gia công.", answer: true, reason: "Gia công phải theo tài liệu chỉ định, không tự ý thay đổi." },
      { id: 10, page: 11, jp: "パイプサポートの すいへいつなぎは たかさ3mごとに とりつけます。", romaji: "Paipu sapoto no suihei-tsunagi wa takasa 3 m goto ni toritsukemasu.", vi: "Giằng ngang pipe support lắp mỗi 3 m chiều cao.", answer: false, reason: "Khoảng cách giằng phải theo quy định/bản vẽ; câu 3 m cố định là sai trong bộ này." },
      { id: 11, page: 11, jp: "パイプサポートを つないで つかうときは 2ほんまでとします。", romaji: "Paipu sapoto o tsunaide tsukau toki wa nihon made to shimasu.", vi: "Khi nối pipe support để dùng thì tối đa hai cây.", answer: true, reason: "Nếu được phép nối thì phải giới hạn số lượng và liên kết đúng; đề nêu tối đa hai cây." },
      { id: 12, page: 11, jp: "はしらの かたわくくみたては てっきんを くみたてる まえに くみたてます。", romaji: "Hashira no katawaku kumitate wa tekkin o kumitateru mae ni kumitatemasu.", vi: "Lắp ván khuôn cột trước khi lắp cốt thép.", answer: false, reason: "Thông thường cốt thép cột được lắp/kiểm tra trước, sau đó mới đóng ván khuôn." },
      { id: 13, page: 11, jp: "パネルと パネルを くぎで とめるときは かならず くぎは うちこんでしまいます。", romaji: "Paneru to paneru o kugi de tomeru toki wa kanarazu kugi wa uchikonde shimaimasu.", vi: "Khi nối panel bằng đinh thì luôn đóng chìm hết đinh.", answer: false, reason: "Cần tính đến tháo dỡ và tái sử dụng, không phải lúc nào cũng đóng chìm hết." },
      { id: 14, page: 11, jp: "かいたいで パイプサポートが じゃまなときは パイプサポートを はずして かいたいします。", romaji: "Kaitai de paipu sapoto ga jama na toki wa paipu sapoto o hazushite kaitai shimasu.", vi: "Khi tháo dỡ, nếu pipe support vướng thì tháo ra rồi tiếp tục tháo.", answer: false, reason: "Không tự ý tháo chống đỡ đang chịu lực; phải theo trình tự và chỉ dẫn an toàn." },
      { id: 15, page: 12, jp: "コンクリートは なるべく はやく かんそうさせた ほうが よいです。", romaji: "Konkurito wa narubeku hayaku kanso saseta ho ga yoi desu.", vi: "Bê tông nên được làm khô càng nhanh càng tốt.", answer: false, reason: "Bê tông cần dưỡng hộ đủ ẩm; khô quá nhanh làm giảm chất lượng và nứt." },
      { id: 16, page: 12, jp: "かたわくようの さんぎには ヨコ27mm×タテ65mmの さんぎを よく つかいます。", romaji: "Katawaku-yo no sangi ni wa yoko 27 mm x tate 65 mm no sangi o yoku tsukaimasu.", vi: "Thanh nẹp ván khuôn thường dùng loại 27 mm × 65 mm.", answer: true, reason: "Đây là kích thước sangi phổ biến được nêu trong tài liệu." },
      { id: 17, page: 12, jp: "きゃたつを つかって さぎょうをするときは きゃたつの いちばんうえに たっても よいです。", romaji: "Kyatatsu o tsukatte sagyo o suru toki wa kyatatsu no ichiban ue ni tattemo yoi desu.", vi: "Khi làm việc trên thang chữ A có thể đứng trên cùng.", answer: false, reason: "Không đứng trên đỉnh/bậc trên cùng của thang chữ A vì nguy cơ ngã cao." },
      { id: 18, page: 12, jp: "いどうしきあしば（ローリングタワー）の うえでは きゃたつを つかっては いけません。", romaji: "Idoshiki ashiba (roringu tawa) no ue de wa kyatatsu o tsukatte wa ikemasen.", vi: "Trên giàn giáo di động không được dùng thang chữ A.", answer: true, reason: "Đặt thang trên rolling tower rất mất ổn định và nguy hiểm." },
      { id: 19, page: 12, jp: "ふんじんのでる さぎょうをするときは ぼうじんマスクを つけます。", romaji: "Funjin no deru sagyo o suru toki wa bojin masuku o tsukemasu.", vi: "Khi làm việc có bụi thì đeo mặt nạ chống bụi.", answer: true, reason: "Mặt nạ chống bụi bảo vệ đường hô hấp khi cắt, mài hoặc dọn bụi." },
      { id: 20, page: 12, jp: "きょうどうさぎょうのときは こえを かけあって さぎょうします。", romaji: "Kyodo sagyo no toki wa koe o kakeatte sagyo shimasu.", vi: "Khi làm việc chung thì gọi/nhắc nhau trong lúc làm.", answer: true, reason: "Gọi tín hiệu khi làm việc chung giúp tránh va chạm và phối hợp an toàn." },
    ],
  },
];
